services:
  db:
    image: postgres:16-alpine
    container_name: 69-s3-db
    ports:
      - "127.0.0.1:${DB_EXTERNAL_PORT:-54327}:5432"
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - ./backup/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:9.16
    container_name: 69-s3-admin
    ports:
      - "127.0.0.1:${PGADMIN_EXTERNAL_PORT:-8083}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./backup/pgadmin:/var/lib/pgadmin

  app:
    image: prawee/strapi
    container_name: 69-s3-app
    ports:
      - "${APP_EXTERNAL_PORT:-9093}:1337" 
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV:-production}
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./backup/app:/opt/app