services:
  db:
    image: postgres:16-alpine
    container_name: 69-s3-db
    ports:
      - "54327:5432"
    environment:
      - POSTGRES_PASSWORD=1p@ssw0rd
      - POSTGRES_USER=danupong
      - POSTGRES_DB=danupong
    volumes:
      - C:/Users/Danup/69-s3-cybersec-databackup/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:9.16
    container_name: 69-s3-admin
    ports:
      - "8083:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - C:/Users/Danup/69-s3-cybersec-databackup/pgadmin:/var/lib/pgadmin
